#!/usr/bin/env bash
# =============================================================================
# update-dotfiles.sh — Smart Environment Updater & Package Diff Manager
#
# Features:
# 1. Package Diffing: Detects newly introduced upstream packages & installs them.
# 2. Granular Config Sync: Updates desktop configs while preserving user state
#    (settings.json, snippets, user preferences).
# 3. Automated Timestamped Backups: Safely archives modified files before updating.
# 4. Live Reload: Refreshes Sway and the b1air shell seamlessly.
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/distro.sh
source "$REPO_DIR/lib/distro.sh"
# shellcheck source=lib/fingerprint.sh
source "$REPO_DIR/lib/fingerprint.sh"
# shellcheck source=lib/wallpapers.sh
source "$REPO_DIR/lib/wallpapers.sh"
BACKUP_ROOT="${HOME}/.dotfiles-backups"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_ROOT}/${TIMESTAMP}"

DRY_RUN=0
AUTO_YES=0
PACKAGES_ONLY=0
CONFIGS_ONLY=0
SKIP_PULL=1

# Protected files that contain user state and should NEVER be overwritten.
# conf.d/custom_*.conf is generated by Settings (input, gaps, appearance and
# the keybinding editor) — the same exclusion install.sh makes.
PROTECTED_FILES=(
    "sway/settings.json"
    "sway/snippets.json"
    "sway/conf.d/custom_"
)

# Colors
RESET="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
YELLOW="\e[33m"
CYAN="\e[36m"
RED="\e[31m"
MAGENTA="\e[35m"

log()  { printf "${CYAN}[INFO]${RESET} %s\n" "$*"; }
ok()   { printf "${GREEN}[OK]${RESET}   %s\n" "$*"; }
warn() { printf "${YELLOW}[WARN]${RESET} %s\n" "$*" >&2; }
err()  { printf "${RED}[ERR]${RESET}  %s\n" "$*" >&2; }

usage() {
    cat <<EOF
${BOLD}DotsFiles Smart Environment Updater${RESET}

Usage: $0 [options]

Options:
  --repo-dir <path>    Specify dotfiles repository path (default: $REPO_DIR)
  --backup-dir <path>  Specify custom backup directory
  --packages-only      Check and install missing packages only
  --configs-only       Update configuration files only (skip package check)
  --pull               Fetch and merge latest git changes before updating
  --dry-run            Show planned actions without modifying any files
  -y, --yes            Non-interactive mode (auto-confirm package installations)
  -h, --help           Show this help message and exit
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --repo-dir)        REPO_DIR="$2"; shift 2 ;;
            --repo-dir=*)      REPO_DIR="${1#--repo-dir=}"; shift ;;
            --backup-dir)      BACKUP_DIR="$2"; shift 2 ;;
            --backup-dir=*)    BACKUP_DIR="${1#--backup-dir=}"; shift ;;
            --packages-only)   PACKAGES_ONLY=1; shift ;;
            --configs-only)    CONFIGS_ONLY=1; shift ;;
            --pull)            SKIP_PULL=0; shift ;;
            --no-pull)         SKIP_PULL=1; shift ;;
            --dry-run)         DRY_RUN=1; shift ;;
            -y|--yes)          AUTO_YES=1; shift ;;
            -h|--help)         usage; exit 0 ;;
            *) err "Unknown option: $1"; usage; exit 1 ;;
        esac
    done
}

ensure_backup_dir() {
    if [[ "$DRY_RUN" -eq 0 ]]; then
        mkdir -p "$BACKUP_DIR"
    fi
}

# ── 1. Git Pull Upstream ──────────────────────────────────────────────────────
#
# Stops the update when the pull cannot happen. It used to warn "Continuing
# with local files" and go on to rebuild and redeploy the commit already
# checked out, so an update that fetched nothing still ended in "✓ Update
# completed successfully!".
pull_upstream() {
    [[ "$SKIP_PULL" -eq 0 ]] || return 0
    [[ -d "$REPO_DIR/.git" ]] || return 0

    log "Checking for updates in $REPO_DIR..."
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "Would run: git -C '$REPO_DIR' pull --ff-only"
        return 0
    fi

    local before upstream changes
    before="$(git -C "$REPO_DIR" rev-parse HEAD)"
    if ! upstream="$(git -C "$REPO_DIR" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null)"; then
        warn "Branch '$(git -C "$REPO_DIR" branch --show-current)' tracks no remote branch; nothing to pull."
        return 0
    fi

    changes="$(git -C "$REPO_DIR" status --porcelain --untracked-files=no)"
    if [[ -n "$changes" ]]; then
        err "Update stopped: these files in $REPO_DIR have local changes:"
        printf '%s\n' "$changes" | sed 's/^/        /' >&2
        err "Commit or stash them (git -C '$REPO_DIR' stash), then update again."
        exit 1
    fi

    if ! GIT_TERMINAL_PROMPT=0 git -C "$REPO_DIR" fetch --quiet; then
        err "Update stopped: could not reach the remote for $upstream (offline, or it needs credentials)."
        exit 1
    fi
    if ! git -C "$REPO_DIR" merge --ff-only --quiet "$upstream" 2>/dev/null; then
        err "Update stopped: this checkout has commits that $upstream does not, so it cannot be fast-forwarded."
        err "Nothing was changed. Look at it with: git -C '$REPO_DIR' log --oneline --graph HEAD $upstream -n 20"
        exit 1
    fi

    if [[ "$(git -C "$REPO_DIR" rev-parse HEAD)" == "$before" ]]; then
        ok "Already up to date with $upstream."
    else
        ok "Updated to $(git -C "$REPO_DIR" rev-parse --short HEAD). New since last time:"
        git -C "$REPO_DIR" log --no-merges --pretty='        %h  %s' "$before..HEAD" | head -n 30
    fi
}

# ── 2. Package Diff & Installation ────────────────────────────────────────────
#
# Reads the same packages/<family>.txt lists install.sh installs from. This
# used to scrape the package arrays out of install.sh with awk, which knew
# only pacman and broke whenever the installer's layout changed.
check_packages() {
    [[ "$CONFIGS_ONLY" -eq 0 ]] || return 0

    log "Analyzing system packages diff..."
    local family
    family="$(detect_distro)"
    if [[ -z "$family" || ! -f "$REPO_DIR/packages/${family}.txt" ]]; then
        warn "Unsupported distribution ($(distro_pretty_name)); skipping package check."
        return 0
    fi

    local list="$REPO_DIR/packages/${family}.txt" pkg
    local missing=() missing_aur=()

    while IFS= read -r pkg; do
        pkg_installed "$family" "$pkg" || missing+=("$pkg")
    done < <(read_package_list "$list" required)
    # Optional packages count only when the repositories actually carry them.
    while IFS= read -r pkg; do
        pkg_installed "$family" "$pkg" && continue
        pkg_available "$family" "$pkg" && missing+=("$pkg")
    done < <(read_package_list "$list" optional)

    if [[ "$family" == "arch" ]] && { command -v yay >/dev/null 2>&1 || command -v paru >/dev/null 2>&1; }; then
        while IFS= read -r pkg; do
            # swayfx and sway are alternatives; a --no-aur install chose sway.
            [[ "$pkg" == "swayfx" ]] && pkg_installed arch sway && continue
            # Ours, built from source into /usr/local (tools/build-swayfx.sh,
            # kept current by update_compositor): the AUR one is only for
            # B1AIR_SWAYFX_FROM_SOURCE=0, as in install.sh. Without this
            # every update had yay build the AUR swayfx all over again, since
            # pacman does not know ours.
            [[ "$pkg" == "swayfx" && ( -x /usr/local/bin/swayfx || "${B1AIR_SWAYFX_FROM_SOURCE:-1}" == "1" ) ]] && continue
            pkg_installed arch "$pkg" || missing_aur+=("$pkg")
        done < <(read_package_list "$REPO_DIR/packages/arch-aur.txt" required)
    fi

    local total_missing=$(( ${#missing[@]} + ${#missing_aur[@]} ))

    if [[ "$total_missing" -eq 0 ]]; then
        ok "All environment packages are installed and up to date."
        return 0
    fi

    printf "\n${YELLOW}${BOLD}Found %d missing / newly added package(s):${RESET}\n" "$total_missing"
    if [[ ${#missing[@]} -gt 0 ]]; then
        printf "  ${CYAN}Repositories (%s):${RESET} %s\n" "$family" "${missing[*]}"
    fi
    if [[ ${#missing_aur[@]} -gt 0 ]]; then
        printf "  ${MAGENTA}AUR:${RESET}               %s\n" "${missing_aur[*]}"
    fi
    printf "\n"

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "Dry run: skipping package installation."
        return 0
    fi

    local do_install=0
    if [[ "$AUTO_YES" -eq 1 ]]; then
        do_install=1
    else
        read -r -p "Install missing package(s)? [Y/n] " reply
        if [[ -z "$reply" || "$reply" =~ ^[Yy]$ ]]; then
            do_install=1
        fi
    fi

    if [[ "$do_install" -eq 1 ]]; then
        if [[ ${#missing[@]} -gt 0 ]]; then
            log "Installing packages from the $family repositories..."
            pm_install "$family" "${missing[@]}" || warn "Some packages failed to install."
        fi

        if [[ ${#missing_aur[@]} -gt 0 ]]; then
            local aur_helper=""
            if command -v yay >/dev/null 2>&1; then aur_helper="yay";
            elif command -v paru >/dev/null 2>&1; then aur_helper="paru"; fi
            log "Installing AUR packages via $aur_helper..."
            "$aur_helper" -S --needed --noconfirm "${missing_aur[@]}" || warn "Some AUR packages failed to install."
        fi
        ok "Package synchronization complete."
    fi
}

# ── 3. Granular Configuration Sync ────────────────────────────────────────────
is_protected() {
    local rel_path="$1"
    for p in "${PROTECTED_FILES[@]}"; do
        if [[ "$rel_path" == "$p" || "$rel_path" == "$p"* ]]; then
            return 0
        fi
    done
    return 1
}

sync_configs() {
    [[ "$PACKAGES_ONLY" -eq 0 ]] || return 0

    log "Synchronizing configuration files..."
    local src_root="$REPO_DIR/.config"
    local dst_root="$HOME/.config"

    [[ -d "$src_root" ]] || { warn "No .config in $REPO_DIR"; return 0; }

    local updated_count=0
    local created_count=0
    local skipped_count=0

    # Compare and copy the repository's .config as it would be deployed on
    # this machine: the binary directory install.sh chose, and on plain sway
    # the swayFX-only lines commented out (see render_config_tree). Copying
    # the raw files put back ~/.local/bin and the effects lines on every
    # update — with a system-wide install that was no daemon, no shell and
    # no working key bindings after the next login.
    local rendered
    rendered="$(mktemp -d)"
    cp -a "$src_root/." "$rendered/"
    render_config_tree "$rendered" "$(b1air_install_prefix)"
    src_root="$rendered"

    while IFS= read -r -d '' src_file; do
        local rel_path="${src_file#"$src_root"/}"
        local dst_file="$dst_root/$rel_path"

        # 1. Skip protected user state files if destination already exists
        if [[ -f "$dst_file" ]] && is_protected "$rel_path"; then
            skipped_count=$((skipped_count + 1))
            continue
        fi

        # 2. If file already exists and is identical, skip
        if [[ -f "$dst_file" ]] && cmp -s "$src_file" "$dst_file"; then
            continue
        fi

        ensure_backup_dir

        if [[ -f "$dst_file" ]]; then
            # File modified upstream -> backup old and update
            if [[ "$DRY_RUN" -eq 1 ]]; then
                log "Would update: ~/.config/$rel_path (backup to $BACKUP_DIR/.config/$rel_path)"
            else
                mkdir -p "$(dirname "$BACKUP_DIR/.config/$rel_path")"
                cp -a "$dst_file" "$BACKUP_DIR/.config/$rel_path"
                mkdir -p "$(dirname "$dst_file")"
                cp -a "$src_file" "$dst_file"
            fi
            updated_count=$((updated_count + 1))
        else
            # New file -> create
            if [[ "$DRY_RUN" -eq 1 ]]; then
                log "Would create: ~/.config/$rel_path"
            else
                mkdir -p "$(dirname "$dst_file")"
                cp -a "$src_file" "$dst_file"
            fi
            created_count=$((created_count + 1))
        fi
    done < <(find "$src_root" -type f -print0)
    rm -rf "$rendered"

    # Wallpapers: added, by category (lib/wallpapers.sh).
    sync_wallpapers "$REPO_DIR" "$DRY_RUN"

    # Desktop entries and icons come with the suite (make install, above);
    # what is left is removing per-user copies an older version put in
    # ~/.local/share/applications, which shadow the installed ones.
    if [[ "$DRY_RUN" -eq 0 ]]; then
        local pruned
        pruned="$(prune_stale_desktop_entries "$BACKUP_DIR")"
        if (( pruned > 0 )); then log "Removed $pruned stale per-user desktop entries"; fi
    fi

    # Fix permissions for scripts
    if [[ "$DRY_RUN" -eq 0 && -d "$HOME/.config/sway/scripts" ]]; then
        find "$HOME/.config/sway/scripts" -type f -name "*.sh" -exec chmod +x {} +
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
        ok "Dry run complete: $updated_count files to update, $created_count new files, $skipped_count user files preserved."
    else
        ok "Configuration sync complete: $updated_count updated, $created_count created, $skipped_count user configs preserved."
        if [[ "$updated_count" -gt 0 ]]; then
            log "Backups archived in: $BACKUP_DIR"
        fi
    fi
}

# ── 4. Live Environment Reload ────────────────────────────────────────────────
reload_environment() {
    [[ "$DRY_RUN" -eq 0 ]] || return 0
    [[ -n "${WAYLAND_DISPLAY:-}" || -n "${SWAYSOCK:-}" ]] || return 0

    log "Reloading desktop environment..."
    if command -v swaymsg >/dev/null 2>&1; then
        swaymsg reload >/dev/null 2>&1 || true
    fi

    # Refresh the shell if running.
    #
    # Was `pgrep quickshell` plus `qs -p ~/.config/quickshell/Main.qml ipc call
    # main close`: the process is b1air-shell, not quickshell, and ~/.config/
    # quickshell is the older QML location (make install deploys to
    # ~/.config/b1air-shell). Neither the test nor the call could ever match, so
    # the shell was never reloaded after an update. The waybar branch that sat
    # above this went with it — this desktop has a native top bar and ships no
    # waybar config.
    if pgrep -x b1air-shell >/dev/null 2>&1; then
        b1air-shell reload 2>/dev/null || true
    fi

    ok "Environment reloaded successfully."
}

# ── 4. Compositor & Suite ─────────────────────────────────────────────────────
#
# Only what changed. The suite build was already incremental, but every
# update printed a "Built target" line for each of its hundred-odd targets and
# copied every binary back over with sudo, so an update that touched one QML
# file read like a full rebuild — and swayfx, the one part that really is
# slow, was never rebuilt at all, so a changed patch reached nobody.

SUITE_STAMP="${XDG_STATE_HOME:-$HOME/.local/state}/b1air/suite-installed"
SUITE_LOG="${XDG_CACHE_HOME:-$HOME/.cache}/b1air/suite-build.log"

# Our swayfx, when this machine runs it: the script keeps a stamp of the
# versions and patches it built, and rebuilds only when those differ.
update_compositor() {
    local script="$REPO_DIR/tools/build-swayfx.sh"
    [[ -x "$script" && -x /usr/local/bin/swayfx ]] || return 0
    if "$script" --check; then
        ok "swayfx is up to date."
        return 0
    fi
    log "swayfx patches or versions changed; rebuilding it (takes a few minutes)..."
    "$script" >&2 || warn "swayfx rebuild failed; keeping the installed one. See ~/.cache/b1air/swayfx-build.log"
}

# Nothing under src/ different from what was last installed: no build, no
# install. Local edits in src/ always count as a change.
suite_unchanged() {
    [[ -f "$SUITE_STAMP" && -d "$REPO_DIR/.git" ]] || return 1
    command -v b1air-daemon >/dev/null 2>&1 || [[ -x "$HOME/.local/bin/b1air-daemon" ]] || return 1
    local last
    last="$(cat "$SUITE_STAMP")"
    git -C "$REPO_DIR" cat-file -e "${last}^{commit}" 2>/dev/null || return 1
    git -C "$REPO_DIR" diff --quiet "$last" HEAD -- src third_party || return 1
    [[ -z "$(git -C "$REPO_DIR" status --porcelain -- src third_party)" ]]
}

# third_party/ holds submodules (podsync, the iPod engine Files uses). A pull
# moves the recorded commit; this checks it out, and fetches it the first time.
sync_submodules() {
    [[ "$DRY_RUN" -eq 1 || ! -f "$REPO_DIR/.gitmodules" ]] && return 0
    GIT_TERMINAL_PROMPT=0 git -C "$REPO_DIR" submodule update --init --quiet \
        || warn "Could not fetch the submodules in third_party/; iPods will not show in Files."
}

update_suite() {
    if suite_unchanged; then
        ok "b1air suite: nothing in src/ changed since it was installed."
        return 0
    fi
    if [[ -f "$SUITE_STAMP" ]] && git -C "$REPO_DIR" cat-file -e "$(cat "$SUITE_STAMP")^{commit}" 2>/dev/null; then
        log "b1air suite: $(git -C "$REPO_DIR" diff --name-only "$(cat "$SUITE_STAMP")" HEAD -- src | wc -l) changed file(s) in src/; rebuilding what depends on them..."
    else
        log "Building b1air suite..."
    fi
    mkdir -p "$(dirname "$SUITE_LOG")"
    # What was compiled, not the hundred "Built target" lines around it.
    if ! make -C "$REPO_DIR/src" -j"$(nproc 2>/dev/null || echo 4)" > "$SUITE_LOG" 2>&1; then
        tail -n 30 "$SUITE_LOG" >&2
        err "Suite rebuild failed. Full log: $SUITE_LOG"
        exit 1
    fi
    local rebuilt
    rebuilt="$(grep -cE 'Building (CXX|C) object' "$SUITE_LOG" || true)"
    grep -E 'Building (CXX|C) object|Linking' "$SUITE_LOG" | sed -E 's/^\[ *[0-9]+%\] /        /' | head -n 40 || true
    ok "Compiled ${rebuilt} file(s)."

    # Install where install.sh put it. A bare `make install` lands in
    # ~/.local/bin, which is ahead of /usr/local/bin on PATH — so after an
    # update the session ran a second, per-user copy of the suite while
    # the system-wide one install.sh had put down went stale.
    if [[ -x /usr/local/bin/b1air-daemon ]]; then
        sudo make -C "$REPO_DIR/src" install \
            PREFIX=/usr/local/bin DATADIR=/usr/share \
            QMLDIR=/usr/share/b1air-shell/qml COMPATDIR=/usr/share/b1air-shell/qs-compat CONFDIR="$HOME/.config" >/dev/null \
            || { err "Suite install failed."; exit 1; }
        sudo chown -R "$USER" "$HOME/.config/environment.d" 2>/dev/null || true
    else
        make -C "$REPO_DIR/src" install >/dev/null || { err "Suite install failed."; exit 1; }
    fi
    if [[ -d "$REPO_DIR/.git" ]]; then
        mkdir -p "$(dirname "$SUITE_STAMP")"
        git -C "$REPO_DIR" rev-parse HEAD > "$SUITE_STAMP"
    fi
    retire_old_apps >/dev/null || true
    ok "b1air suite installed."
}

# The first-run setup (Settings → setup) shows each account the steps it has
# not seen. A desktop installed before the setup existed has been set up by
# hand already, so the steps that came with it count as seen; what an update
# adds later — the fingerprint step, for one — is still shown at next login.
# Which steps those are is in src/shell/qml/settings/setup-steps.json
# ("baseline"), read by b1air-settings itself; it does nothing when the
# account has a marker already.
mark_setup_baseline() {
    [[ "$DRY_RUN" -eq 1 ]] && return 0
    command -v b1air-settings >/dev/null 2>&1 || return 0
    b1air-settings --setup-baseline || warn "Could not mark the setup's steps as seen."
}

main() {
    parse_args "$@"

    [[ -d "$REPO_DIR" ]] || { err "Repo directory not found: $REPO_DIR"; exit 1; }

    printf "\n${BOLD}${CYAN}=== DotsFiles Smart Environment Updater ===${RESET}\n\n"
    pull_upstream
    sync_submodules
    check_packages
    if [[ "$CONFIGS_ONLY" -eq 0 && "$DRY_RUN" -eq 0 ]]; then
        local aur=""
        [[ "$(detect_distro)" == arch ]] && aur="$(command -v yay || command -v paru || true)"
        fingerprint_setup "$(detect_distro)" "${aur##*/}"
    fi
    # ponytail: configs without binaries = stale suite after a source change
    if [[ "$CONFIGS_ONLY" -eq 0 && "$DRY_RUN" -eq 0 ]]; then
        update_compositor
        update_suite
    fi
    sync_configs
    mark_setup_baseline
    reload_environment
    printf "\n${GREEN}${BOLD}✓ Update completed successfully!${RESET}\n\n"
}

main "$@"
