#!/usr/bin/env bash
# =============================================================================
# update-dotfiles.sh — Smart Environment Updater & Package Diff Manager
#
# Features:
# 1. Package Diffing: Detects newly introduced upstream packages & installs them.
# 2. Granular Config Sync: Updates desktop configs while preserving user state
#    (settings.json, snippets, user preferences).
# 3. Automated Timestamped Backups: Safely archives modified files before updating.
# 4. Live Reload: Refreshes Sway and the b1air shell seamlessly.
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/distro.sh
source "$REPO_DIR/lib/distro.sh"
BACKUP_ROOT="${HOME}/.dotfiles-backups"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_ROOT}/${TIMESTAMP}"

DRY_RUN=0
AUTO_YES=0
PACKAGES_ONLY=0
CONFIGS_ONLY=0
SKIP_PULL=1

# Protected files that contain user state and should NEVER be overwritten.
# conf.d/custom_*.conf is generated by Settings (input, gaps, appearance and
# the keybinding editor) — the same exclusion install.sh makes.
PROTECTED_FILES=(
    "sway/settings.json"
    "sway/snippets.json"
    "sway/conf.d/custom_"
)

# Colors
RESET="\e[0m"
BOLD="\e[1m"
GREEN="\e[32m"
YELLOW="\e[33m"
CYAN="\e[36m"
RED="\e[31m"
MAGENTA="\e[35m"

log()  { printf "${CYAN}[INFO]${RESET} %s\n" "$*"; }
ok()   { printf "${GREEN}[OK]${RESET}   %s\n" "$*"; }
warn() { printf "${YELLOW}[WARN]${RESET} %s\n" "$*" >&2; }
err()  { printf "${RED}[ERR]${RESET}  %s\n" "$*" >&2; }

usage() {
    cat <<EOF
${BOLD}DotsFiles Smart Environment Updater${RESET}

Usage: $0 [options]

Options:
  --repo-dir <path>    Specify dotfiles repository path (default: $REPO_DIR)
  --backup-dir <path>  Specify custom backup directory
  --packages-only      Check and install missing packages only
  --configs-only       Update configuration files only (skip package check)
  --pull               Fetch and merge latest git changes before updating
  --dry-run            Show planned actions without modifying any files
  -y, --yes            Non-interactive mode (auto-confirm package installations)
  -h, --help           Show this help message and exit
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --repo-dir)        REPO_DIR="$2"; shift 2 ;;
            --repo-dir=*)      REPO_DIR="${1#--repo-dir=}"; shift ;;
            --backup-dir)      BACKUP_DIR="$2"; shift 2 ;;
            --backup-dir=*)    BACKUP_DIR="${1#--backup-dir=}"; shift ;;
            --packages-only)   PACKAGES_ONLY=1; shift ;;
            --configs-only)    CONFIGS_ONLY=1; shift ;;
            --pull)            SKIP_PULL=0; shift ;;
            --no-pull)         SKIP_PULL=1; shift ;;
            --dry-run)         DRY_RUN=1; shift ;;
            -y|--yes)          AUTO_YES=1; shift ;;
            -h|--help)         usage; exit 0 ;;
            *) err "Unknown option: $1"; usage; exit 1 ;;
        esac
    done
}

ensure_backup_dir() {
    if [[ "$DRY_RUN" -eq 0 ]]; then
        mkdir -p "$BACKUP_DIR"
    fi
}

# ── 1. Git Pull Upstream ──────────────────────────────────────────────────────
pull_upstream() {
    [[ "$SKIP_PULL" -eq 0 ]] || return 0
    [[ -d "$REPO_DIR/.git" ]] || return 0

    log "Checking for git updates in $REPO_DIR..."
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "Would run: git -C '$REPO_DIR' pull --ff-only"
        return 0
    fi

    if git -C "$REPO_DIR" pull --ff-only 2>/dev/null; then
        ok "Git repository is up to date."
    else
        warn "Could not cleanly fast-forward repository. Continuing with local files."
    fi
}

# ── 2. Package Diff & Installation ────────────────────────────────────────────
#
# Reads the same packages/<family>.txt lists install.sh installs from. This
# used to scrape the package arrays out of install.sh with awk, which knew
# only pacman and broke whenever the installer's layout changed.
check_packages() {
    [[ "$CONFIGS_ONLY" -eq 0 ]] || return 0

    log "Analyzing system packages diff..."
    local family
    family="$(detect_distro)"
    if [[ -z "$family" || ! -f "$REPO_DIR/packages/${family}.txt" ]]; then
        warn "Unsupported distribution ($(distro_pretty_name)); skipping package check."
        return 0
    fi

    local list="$REPO_DIR/packages/${family}.txt" pkg
    local missing=() missing_aur=()

    while IFS= read -r pkg; do
        pkg_installed "$family" "$pkg" || missing+=("$pkg")
    done < <(read_package_list "$list" required)
    # Optional packages count only when the repositories actually carry them.
    while IFS= read -r pkg; do
        pkg_installed "$family" "$pkg" && continue
        pkg_available "$family" "$pkg" && missing+=("$pkg")
    done < <(read_package_list "$list" optional)

    if [[ "$family" == "arch" ]] && { command -v yay >/dev/null 2>&1 || command -v paru >/dev/null 2>&1; }; then
        while IFS= read -r pkg; do
            # swayfx and sway are alternatives; a --no-aur install chose sway.
            [[ "$pkg" == "swayfx" ]] && pkg_installed arch sway && continue
            pkg_installed arch "$pkg" || missing_aur+=("$pkg")
        done < <(read_package_list "$REPO_DIR/packages/arch-aur.txt" required)
    fi

    local total_missing=$(( ${#missing[@]} + ${#missing_aur[@]} ))

    if [[ "$total_missing" -eq 0 ]]; then
        ok "All environment packages are installed and up to date."
        return 0
    fi

    printf "\n${YELLOW}${BOLD}Found %d missing / newly added package(s):${RESET}\n" "$total_missing"
    if [[ ${#missing[@]} -gt 0 ]]; then
        printf "  ${CYAN}Repositories (%s):${RESET} %s\n" "$family" "${missing[*]}"
    fi
    if [[ ${#missing_aur[@]} -gt 0 ]]; then
        printf "  ${MAGENTA}AUR:${RESET}               %s\n" "${missing_aur[*]}"
    fi
    printf "\n"

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "Dry run: skipping package installation."
        return 0
    fi

    local do_install=0
    if [[ "$AUTO_YES" -eq 1 ]]; then
        do_install=1
    else
        read -r -p "Install missing package(s)? [Y/n] " reply
        if [[ -z "$reply" || "$reply" =~ ^[Yy]$ ]]; then
            do_install=1
        fi
    fi

    if [[ "$do_install" -eq 1 ]]; then
        if [[ ${#missing[@]} -gt 0 ]]; then
            log "Installing packages from the $family repositories..."
            pm_install "$family" "${missing[@]}" || warn "Some packages failed to install."
        fi

        if [[ ${#missing_aur[@]} -gt 0 ]]; then
            local aur_helper=""
            if command -v yay >/dev/null 2>&1; then aur_helper="yay";
            elif command -v paru >/dev/null 2>&1; then aur_helper="paru"; fi
            log "Installing AUR packages via $aur_helper..."
            "$aur_helper" -S --needed --noconfirm "${missing_aur[@]}" || warn "Some AUR packages failed to install."
        fi
        ok "Package synchronization complete."
    fi
}

# ── 3. Granular Configuration Sync ────────────────────────────────────────────
is_protected() {
    local rel_path="$1"
    for p in "${PROTECTED_FILES[@]}"; do
        if [[ "$rel_path" == "$p" || "$rel_path" == "$p"* ]]; then
            return 0
        fi
    done
    return 1
}

sync_configs() {
    [[ "$PACKAGES_ONLY" -eq 0 ]] || return 0

    log "Synchronizing configuration files..."
    local src_root="$REPO_DIR/.config"
    local dst_root="$HOME/.config"

    [[ -d "$src_root" ]] || { warn "No .config in $REPO_DIR"; return 0; }

    local updated_count=0
    local created_count=0
    local skipped_count=0

    # On plain sway the deployed conf.d has its swayFX-only lines commented out
    # (see strip_swayfx_directives). Compare against a copy treated the same
    # way, or every update would "change" those files back and break sway.
    local fx_free=""
    if [[ -d "$src_root/sway/conf.d" ]] && ! have_swayfx; then
        fx_free="$(mktemp -d)"
        cp -a "$src_root/sway/conf.d/." "$fx_free/"
        strip_swayfx_directives "$fx_free"
    fi

    while IFS= read -r -d '' src_file; do
        local rel_path="${src_file#"$src_root"/}"
        local dst_file="$dst_root/$rel_path"
        if [[ -n "$fx_free" && "$rel_path" == sway/conf.d/*.conf && -f "$fx_free/${rel_path#sway/conf.d/}" ]]; then
            src_file="$fx_free/${rel_path#sway/conf.d/}"
        fi

        # 1. Skip protected user state files if destination already exists
        if [[ -f "$dst_file" ]] && is_protected "$rel_path"; then
            skipped_count=$((skipped_count + 1))
            continue
        fi

        # 2. If file already exists and is identical, skip
        if [[ -f "$dst_file" ]] && cmp -s "$src_file" "$dst_file"; then
            continue
        fi

        ensure_backup_dir

        if [[ -f "$dst_file" ]]; then
            # File modified upstream -> backup old and update
            if [[ "$DRY_RUN" -eq 1 ]]; then
                log "Would update: ~/.config/$rel_path (backup to $BACKUP_DIR/.config/$rel_path)"
            else
                mkdir -p "$(dirname "$BACKUP_DIR/.config/$rel_path")"
                cp -a "$dst_file" "$BACKUP_DIR/.config/$rel_path"
                mkdir -p "$(dirname "$dst_file")"
                cp -a "$src_file" "$dst_file"
            fi
            updated_count=$((updated_count + 1))
        else
            # New file -> create
            if [[ "$DRY_RUN" -eq 1 ]]; then
                log "Would create: ~/.config/$rel_path"
            else
                mkdir -p "$(dirname "$dst_file")"
                cp -a "$src_file" "$dst_file"
            fi
            created_count=$((created_count + 1))
        fi
    done < <(find "$src_root" -type f -print0)
    [[ -n "$fx_free" ]] && rm -rf "$fx_free"

    # Wallpapers sync (non-destructive)
    if [[ -d "$REPO_DIR/.wallpapers" ]]; then
        mkdir -p "$HOME/.wallpapers"
        while IFS= read -r -d '' wp_file; do
            local base_wp
            base_wp="$(basename "$wp_file")"
            if [[ ! -f "$HOME/.wallpapers/$base_wp" ]]; then
                if [[ "$DRY_RUN" -eq 1 ]]; then
                    log "Would add wallpaper: ~/.wallpapers/$base_wp"
                else
                    cp -a "$wp_file" "$HOME/.wallpapers/$base_wp"
                fi
            fi
        done < <(find "$REPO_DIR/.wallpapers" -type f -print0)
    fi

    # Desktop entries. install.sh deploys these; the updater did not, so a
    # renamed or added b1air-*.desktop never reached a machine that only ever
    # runs the updater — and .config/mimeapps.list, which IS synced above,
    # names them as the default handlers for text, directories and images.
    if [[ -d "$REPO_DIR/.local/share/applications" ]]; then
        mkdir -p "$HOME/.local/share/applications"
        local changed_desktop=0
        for entry in "$REPO_DIR"/.local/share/applications/*.desktop; do
            [[ -e "$entry" ]] || continue
            local base_entry dst_entry
            base_entry="$(basename "$entry")"
            dst_entry="$HOME/.local/share/applications/$base_entry"
            if [[ ! -f "$dst_entry" ]] || ! cmp -s "$entry" "$dst_entry"; then
                if [[ "$DRY_RUN" -eq 1 ]]; then
                    log "Would update: ~/.local/share/applications/$base_entry"
                else
                    [[ -f "$dst_entry" ]] && {
                        mkdir -p "$BACKUP_DIR/applications"
                        cp -a "$dst_entry" "$BACKUP_DIR/applications/$base_entry"
                    }
                    cp -a "$entry" "$dst_entry"
                    changed_desktop=1
                fi
            fi
        done
        if [[ "$changed_desktop" -eq 1 ]]; then
            update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
        fi
    fi

    # Fix permissions for scripts
    if [[ "$DRY_RUN" -eq 0 && -d "$HOME/.config/sway/scripts" ]]; then
        find "$HOME/.config/sway/scripts" -type f -name "*.sh" -exec chmod +x {} +
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
        ok "Dry run complete: $updated_count files to update, $created_count new files, $skipped_count user files preserved."
    else
        ok "Configuration sync complete: $updated_count updated, $created_count created, $skipped_count user configs preserved."
        if [[ "$updated_count" -gt 0 ]]; then
            log "Backups archived in: $BACKUP_DIR"
        fi
    fi
}

# ── 4. Live Environment Reload ────────────────────────────────────────────────
reload_environment() {
    [[ "$DRY_RUN" -eq 0 ]] || return 0
    [[ -n "${WAYLAND_DISPLAY:-}" || -n "${SWAYSOCK:-}" ]] || return 0

    log "Reloading desktop environment..."
    if command -v swaymsg >/dev/null 2>&1; then
        swaymsg reload >/dev/null 2>&1 || true
    fi

    # Refresh the shell if running.
    #
    # Was `pgrep quickshell` plus `qs -p ~/.config/quickshell/Main.qml ipc call
    # main close`: the process is b1air-shell, not quickshell, and ~/.config/
    # quickshell is the older QML location (make install deploys to
    # ~/.config/b1air-shell). Neither the test nor the call could ever match, so
    # the shell was never reloaded after an update. The waybar branch that sat
    # above this went with it — this desktop has a native top bar and ships no
    # waybar config.
    if pgrep -x b1air-shell >/dev/null 2>&1; then
        b1air-shell reload 2>/dev/null || true
    fi

    ok "Environment reloaded successfully."
}

main() {
    parse_args "$@"

    [[ -d "$REPO_DIR" ]] || { err "Repo directory not found: $REPO_DIR"; exit 1; }

    printf "\n${BOLD}${CYAN}=== DotsFiles Smart Environment Updater ===${RESET}\n\n"
    pull_upstream
    check_packages
    # ponytail: configs without binaries = stale suite after a source change
    if [[ "$CONFIGS_ONLY" -eq 0 && "$DRY_RUN" -eq 0 ]]; then
        log "Rebuilding b1air suite..."
        make -C "$REPO_DIR/src" -j"$(nproc 2>/dev/null || echo 4)" || { err "Suite rebuild failed."; exit 1; }
        # Install where install.sh put it. A bare `make install` lands in
        # ~/.local/bin, which is ahead of /usr/local/bin on PATH — so after an
        # update the session ran a second, per-user copy of the suite while
        # the system-wide one install.sh had put down went stale.
        if [[ -x /usr/local/bin/b1air-daemon ]]; then
            sudo make -C "$REPO_DIR/src" install \
                PREFIX=/usr/local/bin DATADIR=/usr/share \
                QMLDIR=/usr/share/b1air-shell/qml CONFDIR="$HOME/.config" >/dev/null \
                || { err "Suite install failed."; exit 1; }
            sudo chown -R "$USER" "$HOME/.config/environment.d" 2>/dev/null || true
        else
            make -C "$REPO_DIR/src" install || { err "Suite install failed."; exit 1; }
        fi
    fi
    sync_configs
    reload_environment
    printf "\n${GREEN}${BOLD}✓ Update completed successfully!${RESET}\n\n"
}

main "$@"
