################
### MONITORS ###
################
# Docs: https://man.archlinux.org/man/sway-output.5

output Virtual-1 mode 1280x800 position 0 0 max_render_time 33
output HEADLESS-1 mode 1280x800 position 0 0 max_render_time 33

exec_always $b1airBin/b1air-daemon monitors restore
