pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// =============================================================================
// The settings that are really sway's, written where sway will find them.
//
// Three settings pages — Mouse & Touchpad, Window & Gaps, Appearance — change
// the compositor by running `swaymsg`. That works on the running session and
// nowhere else: sway builds its configuration from conf.d at startup, and
// nothing read the saved values back. Gaps, borders, corner radius, blur,
// shadows, dimming, pointer speed, scrolling — all of it reverted at the next
// login while the toggles kept showing what the user had picked.
//
// So the pages keep applying live, and this writes the same state into
// conf.d/custom_*.conf for the next session. sway's config includes
// `custom_*.conf` after everything else, so a generated file overrides the
// shipped defaults in input.conf and look-and-feel.conf without editing a file
// the user might have their own changes in.
//
// One place rather than one per page: the two files are small, the values come
// from the same Settings singleton, and three copies of "render a sway config"
// is how they drift.
// =============================================================================

Singleton {
    id: root

    readonly property string confDir: Quickshell.env("HOME") + "/.config/sway/conf.d"

    readonly property string header:
        "# Generated by b1air Settings. Rewritten whenever a control on the\n" +
        "# matching page is used, so hand edits here do not survive; the shipped\n" +
        "# defaults are in conf.d/input.conf and conf.d/look-and-feel.conf, and\n" +
        "# this file is included after them.\n\n"

    function _onOff(v) { return v ? "enabled" : "disabled"; }

    // Both writers are deferred a moment rather than run on the spot.
    //
    // A page calls `Settings.set("smartGaps", true)` and then asks for a
    // rewrite, and reading `Settings.smartGaps` back at that instant still
    // gives the old value — the write has not propagated through the alias
    // yet. Measured: a generated file with every setting correct except the
    // one that had just been changed, which is the worst possible shape for
    // this bug because five settings out of six look right.
    //
    // The delay also collapses a held-down stepper into one write instead of
    // one per repeat.
    /**
     * The four-finger set, as [gesture, sway command] pairs — one list for
     * the config file and the Settings page's runtime binding alike.
     *
     *   up          the Launchpad, every app at a glance
     *   down        close whatever panel is open
     *   left/right  carry the focused window to the neighbouring workspace
     *               and follow it there
     */
    function fourFingerGestures(natural) {
        const left = natural ? "prev" : "next";
        const right = natural ? "next" : "prev";
        return [
            ["swipe:4:up", "exec b1air-shell toggle launchpad"],
            ["swipe:4:down", "exec b1air-shell close"],
            // Two commands: written bare in a config file, where the rest of
            // the line is the binding; quoted when sent through swaymsg (see
            // InputSettingsSection._applyFourFinger).
            ["swipe:4:left", "move container to workspace " + left + "; workspace " + left],
            ["swipe:4:right", "move container to workspace " + right + "; workspace " + right]
        ];
    }

    function writeInput() { inputDebounce.restart(); }
    function writeLook() { lookDebounce.restart(); }

    Timer {
        id: inputDebounce
        interval: 150
        onTriggered: root._renderInput()
    }

    Timer {
        id: lookDebounce
        interval: 150
        onTriggered: root._renderLook()
    }

    // ── Mouse & Touchpad ─────────────────────────────────────────────────────

    function _renderInput() {
        let out = root.header;

        out += "input type:pointer {\n";
        out += "    accel_profile \"" + (Settings.accelProfile || "flat") + "\"\n";
        out += "    pointer_accel " + Number(Settings.pointerAccel || 0) + "\n";
        out += "    left_handed " + root._onOff(Settings.leftHanded) + "\n";
        out += "}\n\n";

        out += "input type:touchpad {\n";
        out += "    natural_scroll " + root._onOff(Settings.naturalScroll) + "\n";
        out += "    tap " + root._onOff(Settings.tapToClick) + "\n";
        out += "    click_method " + (Settings.touchpadClickfinger ? "clickfinger" : "button_areas") + "\n";
        out += "    dwt " + root._onOff(Settings.dwt) + "\n";
        out += "    pointer_accel " + Number(Settings.pointerAccel || 0) + "\n";
        out += "}\n";

        if (Settings.touchpadSwipeWorkspace) {
            // "Natural" means the workspace follows the fingers, the way
            // dragging a sheet of paper does, so the two bindings swap.
            const left = Settings.touchpadNaturalSwipe ? "prev" : "next";
            const right = Settings.touchpadNaturalSwipe ? "next" : "prev";
            out += "\nbindgesture swipe:3:left workspace " + left + "\n";
            out += "bindgesture swipe:3:right workspace " + right + "\n";
        } else {
            // input.conf binds the defaults and this file is read after it:
            // switched off has to be said, not left out, or the default stays.
            out += "\nunbindgesture swipe:3:left\nunbindgesture swipe:3:right\n";
        }

        for (const g of root.fourFingerGestures(Settings.touchpadNaturalSwipe))
            out += Settings.touchpadFourFinger ? "bindgesture " + g[0] + " " + g[1] + "\n"
                                               : "unbindgesture " + g[0] + "\n";

        inputWriter.path = root.confDir + "/custom_input.conf";
        inputWriter.setText(out);
    }

    // ── Window & Gaps, Appearance ────────────────────────────────────────────

    function _renderLook() {
        let out = root.header;

        out += "gaps inner " + Number(Settings.gapsInner) + "\n";
        out += "gaps outer " + Number(Settings.gapsOuter) + "\n";
        // `gaps outer` sets all four edges, so the top has to be put back
        // after it — see conf.d/look-and-feel.conf for why that edge is zero.
        out += "gaps top 0\n";
        out += "default_border pixel " + Number(Settings.borderWidth) + "\n";
        out += "smart_gaps " + (Settings.smartGaps ? "on" : "off") + "\n";
        out += "smart_borders " + (Settings.smartBorders ? "on" : "off") + "\n\n";

        // SwayFX only. Plain sway rejects the whole config file on an unknown
        // command, so these are written exactly as look-and-feel.conf already
        // writes them — a machine that parses that file parses this one.
        out += "corner_radius " + Number(Settings.cornerRadius) + "\n";
        out += "blur " + (Settings.blurEnabled ? "enable" : "disable") + "\n";
        out += "shadows " + (Settings.shadowsEnabled ? "enable" : "disable") + "\n";
        // 0.20 is the value look-and-feel.conf ships and the value the toggle
        // on the Appearance page describes ("Enabled (20% dimming)"); it is
        // written here so the toggle's off state survives a logout too.
        //
        // The schema's `inactiveOpacity` looked like the place to get an
        // amount from, and it is not: nothing had ever read it, its default of
        // 1.0 is the opposite polarity to `default_dim_inactive`, and taking
        // it at face value would have dimmed every unfocused window to black.
        // It is gone rather than guessed at.
        out += "default_dim_inactive " + (Settings.dimInactive ? "0.20" : "0.0") + "\n";

        lookWriter.path = root.confDir + "/custom_look.conf";
        lookWriter.setText(out);
    }

    FileView {
        id: inputWriter
        printErrors: false
        atomicWrites: true
    }

    FileView {
        id: lookWriter
        printErrors: false
        atomicWrites: true
    }
}
